default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root

development:
  <<: *default
  database: cuckoo_development

test:
  <<: *default
  database: cuckoo_test

production:
  <<: *default
  database: cuckoo_production
